name: "myaction"
description: "My Custom Action"

inputs:
  repository:
    description: "repo owner /name"
    default: ${{ github.repository }}
  token:
    description: "GitHub Token"
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        export PYTHONPATH=${{ github.action_path }}:${{ github.action_path }}/vendor
        python3 -m myaction \
            --github-repository="${{ inputs.repository }}" \
            --github-token="${{ inputs.token }}"
