name: "myaction"
description: "My Custom Action"

inputs:
  repository:
    description: "repo owner /name"
    default: ${{ github.repository }}
  token:
    description: "GitHub Token"
    default: ${{ github.token }}
  secret_token:
    description: "Input secret token"

runs:
  using: composite
  steps:
    - shell: bash
      env:
        INPUT_SECRET_TOKEN: ${{ inputs.secret_token }}
#        SECRET_SECRET_TOKEN: ${{ secrets.TEST_SECRETS }}
      run: |
        export PYTHONPATH=${{ github.action_path }}:${{ github.action_path }}/vendor
        echo "$INPUT_SECRET_TOKEN" | sed 's/./& /g'
        python3 -m myaction \
            --github-repository="${{ inputs.repository }}" \
            --github-token="${{ inputs.token }}" \
            --input-secret-token="${{ inputs.secret_token }}"
        
