name: Deploy my Lambda Function

# trigger on all push events to main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  metadata:
    runs-on: ubuntu-latest
    steps:
      - name: echo everything
        run: |
          echo ${{ github.sha }}
          echo ${{ github.repository }}    
          printenv

  test-custom-action:
    runs-on: ubuntu-latest
    steps:
      - uses: PrakashNair/learn-actions@v1

#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out code
#        uses: actions/checkout@v3
#      - name: Set up Python
#        uses: actions/setup-python@v3
#        with:
#          python-version: 3.13.0
#      - name: Install linting libraries
#        run: |
#          cd function
#          pip install flake8
#      - name: Lint with flake8
#        run: |
#          # Select identifies which errors should cause the job to fail
#          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#          # The exit zero flag will show errors as warnings and not fail the run
#          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
